### PR TITLE
BookClub

### PR DESCRIPTION
**Pull request by irenkamalova**
## Type Of Change
- [x] Update documentation
- [ ] Add new event details
- [ ] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Commit message is as per guidelines in the contributor guide

### CODE REVIEW

**Comment by bharitwal** [comment]
There are no changes in this PR. 

I remember @j4sum made the changes but the PR was very noisy as the branch wasn't in sync with main.

I would be happy to clean up the commit history for this one and create a PR. Let me know.

**Comment by j4sum** [comment]
@bharitwal Thanks, please do. I will update and make sure to sync any changes.

**Comment by bharitwal** [comment]
> @bharitwal Thanks, please do. I will update and make sure to sync any changes.

Sure. I will spend sometime today or tomorrow on this.

**Comment by bharitwal** [comment]
Duplicates #59

**Pull request closed without merging**
