### PR TITLE
Create book-club.md

### PR DESCRIPTION
**Pull request by j4sum**
Update book-club.md with info regarding book-club

## Type Of Change
- [ ] Update documentation
- [ ] Add new event details
- [x] Add project resources

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Commit message is as per guidelines in the contributor guide

### CODE REVIEW

**Comment by j4sum** [comment]
Adding bookclub resources on the main.

**Comment by irenkamalova** [comment]
I love it!
I can suggest to add Nadia's talk about the Culture Map: https://www.youtube.com/watch?v=bSdm4sd5sh4
She prepared it before she hosted those book club session.

For Quite, we have a blog post at WWCode: https://www.womenwhocode.com/blog/quiet-book-club-wwcode-london

**Review by irenkamalova — APPROVED** [review]

**Review by bharitwal — CHANGES_REQUESTED** [review]
This looks great. Thanks for this @j4sum.

1 recommendation would be to change the name of the file to README.md. It helps display information about this resource directory by default without requiring an additional click on the file named book-club.md .

**Comment by bharitwal** [comment]
@j4sum   - Can we close this PR. As its addressed by #38

**Comment by j4sum** [comment]
Successfully merged changes.

**Pull request closed without merging**
